/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-24 12:47:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/category.jsp", Long.valueOf(1642771524000L));
    _jspx_dependants.put("/views/login.jsp", Long.valueOf(1642771372000L));
    _jspx_dependants.put("/views/menu.jsp", Long.valueOf(1642726200000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        header{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            background-color: rgb(220, 241, 250);\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        header>h1{\r\n");
      out.write("            padding-left: 20px;\r\n");
      out.write("            color: rgb(71, 188, 241);\r\n");
      out.write("        }\r\n");
      out.write("        nav{\r\n");
      out.write("            background:green;\r\n");
      out.write("            color: azure;\r\n");
      out.write("            box-shadow: gray;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            padding-top: 1px;\r\n");
      out.write("            border-top: 2px solid rgb(71, 188, 241);\r\n");
      out.write("    		border-bottom: 2px solid rgb(71, 188, 241);\r\n");
      out.write("        }\r\n");
      out.write("        article{\r\n");
      out.write("            min-height: 400px;\r\n");
      out.write("            width: 75%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        aside{\r\n");
      out.write("            min-height: 200px;\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("        aside>.login{\r\n");
      out.write("            margin: 10px 0px 10px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 20px 0px 20px 0px;\r\n");
      out.write("            border: 3px solid rgb(71, 188, 241);\r\n");
      out.write("            color: rgb(71, 188, 241);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        aside>.category{\r\n");
      out.write("            margin: 10px 0px 10px 20px;\r\n");
      out.write("            padding: 20px 0px 20px 0px;\r\n");
      out.write("            border: 3px solid rgb(71, 188, 241);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        footer{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            padding-top: 5px;\r\n");
      out.write("            background: gainsboro;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            clear: both;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <h1>Online Shopping Mall</h1>\r\n");
      out.write("            \r\n");
      out.write("        </header>\r\n");
      out.write("        <nav>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	.hmenu{\r\n");
      out.write("	    list-style: none;\r\n");
      out.write("	}\r\n");
      out.write("	.hmenu>li{\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    margin-right: 44px;\r\n");
      out.write("	    color: blue;\r\n");
      out.write("	}\r\n");
      out.write("	.hmenu>a{\r\n");
      out.write("        Font-variant:small-caps;\r\n");
      out.write("        color:blue;\r\n");
      out.write("        Text-decoration:none;\r\n");
      out.write("    }\r\n");
      out.write("    .hmenu>a:visited{\r\n");
      out.write("        Color:green;\r\n");
      out.write("    }\r\n");
      out.write("    .hmenu>a:hover{\r\n");
      out.write("        Color:red;\r\n");
      out.write("        Text-decoration:underline;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"/menu.jsp\">\r\n");
      out.write("		<ul class=\"hmenu\">\r\n");
      out.write("	    	<li><a href=\"#1\">Home</a></li>\r\n");
      out.write("	    	<li><a href=\"#2\">About Us</a></li>\r\n");
      out.write("	    	<li><a href=\"#3\">Contact Us</a></li>\r\n");
      out.write("	    	<li><a href=\"#4\">Feedback</a></li>\r\n");
      out.write("	    	<li><a href=\"#5\">FAQs</a></li>\r\n");
      out.write("   		</ul>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("        <article>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "item.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("laptop Microsoft Surface", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("image", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hinh1.jpg", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "item.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("laptop Microsoft Surface", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("image", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hinh1.jpg", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "item.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("laptop Microsoft Surface", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("image", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hinh1.jpg", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "item.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("laptop Microsoft Surface", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("image", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hinh1.jpg", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "item.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("laptop Microsoft Surface", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("image", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hinh1.jpg", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "item.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("name", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("laptop Microsoft Surface", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("image", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("hinh1.jpg", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("        </article>\r\n");
      out.write("        <aside>\r\n");
      out.write("            <div class=\"login\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"/login\">\r\n");
      out.write("		<input name=\"username\"><br><br>\r\n");
      out.write("		<input name=\"password\"><br>\r\n");
      out.write("		<input name=\"remember\" type=\"checkbox\">Remember me?\r\n");
      out.write("		<hr>\r\n");
      out.write("		<button style=\"color: rgb(71, 188, 241)\">Login</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"category\">\r\n");
      out.write("            	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	.vmenu{\r\n");
      out.write("                padding: 0px;\r\n");
      out.write("                margin: 5px;\r\n");
      out.write("                list-style: none;\r\n");
      out.write("                border-radius: 3px;\r\n");
      out.write("                box-shadow:0 0 2px gray;\r\n");
      out.write("                list-style: none;\r\n");
      out.write("            }\r\n");
      out.write("            .vmenu a{\r\n");
      out.write("                background: url(\"#1\") no-repeat 2px center;\r\n");
      out.write("                display: block;\r\n");
      out.write("                border-bottom: 1px solid rgb(71, 188, 241);\r\n");
      out.write("                color: blue;\r\n");
      out.write("                font-variant: small-caps;\r\n");
      out.write("                font-size: larger;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                padding: 8px 5px 8px 30px;\r\n");
      out.write("            }\r\n");
      out.write("            .vmenu a:hover{\r\n");
      out.write("                background: url(\"#1\") no-repeat 2px center;\r\n");
      out.write("                border-bottom: 1px dotted white;\r\n");
      out.write("                background-color: orangered;\r\n");
      out.write("                color: white;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("            }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"/category.jsp\">\r\n");
      out.write("		<ul class=\"vmenu\">\r\n");
      out.write("            <li><a href=\"#\">LOẠI SẢN PHẨM 1</a></li>\r\n");
      out.write("            <li><a href=\"#\">LOẠI SẢN PHẨM 2</a></li>\r\n");
      out.write("            <li><a href=\"#\">LOẠI SẢN PHẨM 3</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </aside>\r\n");
      out.write("        <footer>\r\n");
      out.write("            <p>FPT Polytechnic @2020. All right reserved.</p>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
